name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Ou a branch que preferir

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Construir a imagem Docker
        run: docker build -t usuario/woofed-matheus:latest .

      - name: Fazer login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Enviar a imagem para o Docker Hub
        run: docker push usuario/woofed-matheus:latest
